ALTER TABLE "billing_items" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "billing_items" ALTER COLUMN "billing_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "billing_items" ALTER COLUMN "item_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "billings" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "billings" ALTER COLUMN "visit_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "discharge_summaries" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "discharge_summaries" ALTER COLUMN "visit_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "payments" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "payments" ALTER COLUMN "billing_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "services" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "roles" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "user_roles" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "user_roles" ALTER COLUMN "role_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "patients" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "polis" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "visits" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "visits" ALTER COLUMN "patient_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "visits" ALTER COLUMN "poli_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "visits" ALTER COLUMN "room_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "cppt" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "cppt" ALTER COLUMN "visit_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "diagnoses" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "diagnoses" ALTER COLUMN "medical_record_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "medical_records" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "medical_records" ALTER COLUMN "visit_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "procedures" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "procedures" ALTER COLUMN "medical_record_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "procedures" ALTER COLUMN "service_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "drug_inventory" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "drug_inventory" ALTER COLUMN "drug_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "drugs" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "prescriptions" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "prescriptions" ALTER COLUMN "medical_record_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "prescriptions" ALTER COLUMN "drug_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "prescriptions" ALTER COLUMN "inventory_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "inventory_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "reference_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "bed_assignments" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "bed_assignments" ALTER COLUMN "visit_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "bed_assignments" ALTER COLUMN "room_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "material_usage" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "material_usage" ALTER COLUMN "visit_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "rooms" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "vitals_history" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "vitals_history" ALTER COLUMN "visit_id" SET DATA TYPE text;