/**
 * Compound Recipe Types
 * Types for compound medication (obat racik) feature
 */

/**
 * Single ingredient in a compound recipe
 */
export interface CompoundIngredient {
  drugId: string
  drugName: string
  quantity: number
  unit: string
  price?: number // Drug price per unit (for cost calculation, optional)
}

/**
 * Compound Recipe (Master Data)
 * Template for compound medications
 */
export interface CompoundRecipe {
  id: string
  code: string
  name: string
  description?: string | null
  composition: CompoundIngredient[]
  defaultInstructions?: string | null
  defaultFrequency?: string | null
  price?: string | null
  isActive: boolean
  createdBy?: string | null
  createdAt: Date
  updatedAt: Date
}

/**
 * Compound Recipe with creator info
 */
export interface CompoundRecipeWithCreator extends CompoundRecipe {
  creator?: {
    id: string
    name: string
  } | null
}

/**
 * Filters for compound recipe queries
 */
export interface CompoundRecipeFilters {
  search?: string
  isActive?: boolean
}

/**
 * Input for creating a compound recipe
 * Note: code is auto-generated by the server
 */
export interface CreateCompoundRecipeInput {
  name: string
  description?: string
  composition: CompoundIngredient[]
  defaultInstructions?: string
  defaultFrequency?: string
  price: number
}

/**
 * Input for updating a compound recipe
 */
export interface UpdateCompoundRecipeInput {
  code?: string
  name?: string
  description?: string | null
  composition?: CompoundIngredient[]
  defaultInstructions?: string | null
  defaultFrequency?: string | null
  price?: number | null
  isActive?: boolean
}

/**
 * Compound prescription - extends normal prescription with compound fields
 */
export interface CompoundPrescriptionData {
  compoundRecipeId: string
  compoundRecipe?: CompoundRecipe
  quantity: number
  frequency: string
  duration?: string
  instructions?: string
}
